services:
  postgres:
    image: postgres:15  
    restart: always
    environment:
      POSTGRES_USER: admin          
      POSTGRES_PASSWORD: admin  
      POSTGRES_DB: users_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    container_name: postgres_db
    networks:
      - app_network

  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
    depends_on:
      - postgres
    container_name: telegramsmsbridge.api
    networks:
      - app_network
    
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - telegramsmsbridge.api
    container_name: nginx
    networks:
      - app_network
   
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    ports:
      - 4040:4040
    depends_on:
      - nginx
    container_name: ngrok
    networks:
      - app_network

networks:
  app_network:
    driver: bridge