services:
  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
    container_name: telegramsmsbridge.api
    networks:
      - app_network

  nginx:
    image: nginx:latest
    depends_on:
      - telegramsmsbridge.api
    links:
      - "telegramsmsbridge.api"
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    container_name: nginx
    networks:
      - app_network
  
  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - nginx
    command:
      - "http"
      - "--url=donkey-large-rodent.ngrok-free.app"
      - "http://api.prop.loc"
    environment:
      NGROK_AUTHTOKEN: 2n9K1ObXBZA7uwnECLII6RtUEKu_6bUbeUWM1Kp23E3N8gG1f
    ports:
      - 4040:4040 
    container_name: ngrok
    networks:
      - app_network

networks:
  app_network:
    driver: bridge