services:
  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
  
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: 2n9K1ObXBZA7uwnECLII6RtUEKu_6bUbeUWM1Kp23E3N8gG1f
    command:
      - "http"
      - "--url=donkey-large-rodent.ngrok-free.app"
      - "5000"
    ports:
      - 4040:4040
    depends_on:
      - telegramsmsbridge.api