services:
  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--url=donkey-large-rodent.ngrok-free.app"
      - "http://host.docker.internal:5000"
    environment:
      NGROK_AUTHTOKEN: 2n9K1ObXBZA7uwnECLII6RtUEKu_6bUbeUWM1Kp23E3N8gG1f
    ports:
      - 4040:4040