version: '3.8'

services:
  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
    ports:
      - "8080:8080"
    restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - telegramsmsbridge.api
    ports:
      - "80:80"  # Expose NGINX on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount a custom NGINX configuration file
    restart: always
  
  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - nginx
    command:
      - "http"
      - "--url=donkey-large-rodent.ngrok-free.app"
      - "http://telegramsmsbridge.webservice"
    environment:
      NGROK_AUTHTOKEN: 2n9K1ObXBZA7uwnECLII6RtUEKu_6bUbeUWM1Kp23E3N8gG1f
    ports:
      - 4040:4040 