services:
  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
    container_name: telegramsmsbridge.api
    networks:
      - app_network
    
  nginx:
    image: nginx:latest
    restart: unless-stopped
    links:
      - telegramsmsbridge.api
    ports:
      - "8080:8080" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - telegramsmsbridge.api
    container_name: nginx
    networks:
      - app_network
  
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    depends_on:
      - nginx
    ports:
      - 4040:4040
    container_name: ngrok
    networks:
      - app_network

networks:
  app_network:
    driver: bridge