services:
  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
    container_name: telegramsmsbridge.api
    networks:
      net:
        ipv4_address: 200.0.0.2

  nginx:
    image: nginx:latest
    depends_on:
      - telegramsmsbridge.api
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    container_name: nginx
    networks:
      net:
        ipv4_address: 200.0.0.3
  
  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - nginx
    command:
      - "http"
      - "--url=donkey-large-rodent.ngrok-free.app"
      - "http://api.smsmonitor.com"
    environment:
      NGROK_AUTHTOKEN: 2n9K1ObXBZA7uwnECLII6RtUEKu_6bUbeUWM1Kp23E3N8gG1f
    ports:
      - 4040:4040 
    container_name: ngrok
    networks:
      net:
        ipv4_address: 200.0.0.4

networks:
  net:
    ipam:
      driver: bridge
      config:
        - subnet: 200.0.0.0/8
          gateway: 200.0.0.1