services:
  telegramsmsbridge.api:
    image: ${DOCKER_REGISTRY-}telegramsmsbridgeapi
    build:
      context: .
      dockerfile: TelegramSmsBridge.API/Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
